# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Shared' do

  # Pods for Shared
  pod 'HTTPNetworking', :git => 'https://github.com/ned1988/HttpNetworking.git'

end
